---
language: python
env:
  global:
  - secure: "tITH79teDMw/NygSkhtViC4WyXW4L4+NSRSp0LZdJSSg30hiCxCUEawzpoX4UzR8un4tzb7Sz1YXYh9uCrKe6ktWBz3wI38SJNXJKxlcAs5P6EouwS+TLLz0d0DPO7f8B0kPoVFpZdDrDP3BizPMNA0VSiAT9Iuuk6M/+YvG4KqAbh7+uIoPshhRMdCH5SN9uIGvZm1hiGrovpO0y+8vDytj2gQHOSlZWu3tRrdsO3eoGMmFVI8sXjtXpUIn0Z/X4KWUkee5xonnlhYb+W2bTopYMZKKApT5pzJo7YZ38R7NVqiEcP4DROmq64B9aTn7cpZyqVaIRZTZ7DBrSNxW9sls62XOxermFqVXbBxL8LJjBYrWixcM+/+SpdOKq6jI5m8uf4cXgPiwr3xe7liprqtwCiYQulaoBfT2bgC9pcp59omtsqxlbHnar8HnGyM8ZqZzA47F/NddFhSPWeDshs0rGEtxdyaZsXAN3l4J1U25VnBJdMc/PQt/EZXgSpVpG3ovPkJ2HppJX/TMz/n14qoeIuZ98C3X7XLCnIjeTyfA6RziKct/XhAUF0wBeIgcGf+m4JYPJ4YGudvKdZLCM28E6CycPFvnKvdS0wRud886GGC1SmTQbspcaRAid0nKjj3oceXDnevE9r412Cd64PxbLCK2MFd07VPaoZ4X9AA=" # AWS_ACCESS_KEY_ID=xyz
  - secure: "Kr6TISThqzq2TzALAHZNfXrDKy/viQSLAO+fX3gmF2xLfkSA9OdkVnFDmYDVSjJW4AUX8wq/B8CIr2cF6Fnu8dAO/z61CaXZlaHWeT58Raxsa+LD6TRUJM1tkTZdMNGC8zvh2H9xma+x1swuxCGt3zBOOmT3TWEnC2VPpGKFM1y2yem/zarJuiS6yL8x6QQSkMafQbX6gqst8Eh1fBKNnuwVdnYDU2R/f4ZpR/v2WmeHlxlSPT6ZtgLkiVAlGWIIlRicubOmKXSCdM+8GO/gUZSwQwUVjs8zzB2/Nv7rucjqfPEw1mADKxEXrnRIpsd+LsLFfVtZPOyEXsurTyIZkqjYWbzi1bqmv8q39h046Wq/IjfhppM5UJKjAc2c5ekKWf9kC9+kCTGklP8xzX+cnH2xG10roLv9yvcfIur6iqmdsYAsfWeRri2xMEG1m+N6ojKxD4Hn1WXxy9D4ZnggEzKnDJzyLUFDOAxGe6Jo341s6O5Gv6U9IOEIB8BwvEE1XEzJvo4lYRe3LK89zKnCNHJPcTTr7Qm30Xv8YTY/1iir6BFh0VtJDHLUF+Xv/HfZcL1Gy+oVaR98d91aL5vIL5lx4jufIrmrjyoo/BUXuQkVoScaRW0yiXTTm0ScVhj5W5yUjBG2LG/bZ2TVzYttNeu+GzKim3iqfo/wsO2MfiA=" # AWS_SECRET_ACCESS_KEY=xyz
  - 'AWS_DEFAULT_REGION=us-east-1'
python:
- '2.7'
install:
- 'pip install yamllint==1.13.0'
- 'pip install awscli==1.16.69'
script:
- 'yamllint .'
- 'find . -type f \( -name ''*.yml'' -o -name ''*.yaml'' \) -a ! -name ''.*'' | while read file; do set -ex && grep -q "LICENSE-2.0" "$file"; done;'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then find . -type f \( -name ''*.yml'' -o -name ''*.yaml'' \) -a ! -name ''.*'' | while read file; do set -ex && aws cloudformation validate-template --template-body "file://$file" > /dev/null; done; fi'
